name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reemplazar variables de entorno
        run: |
          sed -i "s|{{MQTT_BROKER_URL}}|${{ vars.MQTT_BROKER_URL }}|g" dashboard.html
          sed -i "s|{{MQTT_USERNAME}}|${{ vars.MQTT_USERNAME }}|g" dashboard.html
          sed -i "s|{{MQTT_PASSWORD}}|${{ secrets.MQTT_PASSWORD }}|g" dashboard.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
